### PR TITLE
updated to lock v10, added logout button

### PR DESCRIPTION
**Pull request by Amialc**
Related to https://github.com/auth0/auth0-PHP/issues/96

### CODE REVIEW

**Comment by mpaktiti** [comment]
@chenkie Can you please have someone look into this? Thank you!

**Comment by glena** [comment]
auth0-php v4 changed some things on the API.

I updated the example https://github.com/auth0/auth0-PHP/tree/master/examples/basic-oauth so this one needs to be updated.

The old API will continue working but will be deprecated soon

**Comment by mpaktiti** [comment]
@iannyanes ^

**Comment by Amialc** [comment]
@mpaktiti @glena done

**Comment by mpaktiti** [comment]
@chenkie ^

**Pull request merged**
